Создание заказа, обновление заказа по callback_url
Komtet/komtet-kassa-bitrix-delivery pull request #5
Opened 2019-06-04 14:27 UTC by alexandrmotmom

2019-06-05 07:42 UTC, keipaglows requested changes

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        if (!gettype($order) == 'object')
Может лучше не от противного делать проверку?
```
        if (gettype($order) == 'object')
        {
             $orderId = $order->getFieldValues()["ORDER_ID"];
             $ok = new KomtetDeliveryD7();
             $ok->createOrder($orderId);
        }
```

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +
Пустая строка

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        $this->payStatus = 'Y';
Стоит вынести в константу.

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +
Пустая строка.

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +                                                           'price' => round($position->getPrice(),2),
Пробел после запятой между аргументами `round`

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +                                                           'total'=> round($position->getFinalPrice(),2),
Пробел после запятой между аргументами `round`

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +                                                               'measure_name' => "шт",
Стоит вынести в константы.

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +
Лишняя пустая строка.

2019-06-05 07:42 UTC, keipaglows commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        if(!CModule::IncludeModule("sale"))
Нет пробела после `if` здесь, и в некоторых других местах.

2019-06-05 09:15 UTC, mini4 commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        if (!gettype($order) == 'object')
я боюсь что это условие никогда не будет истинным, т.к. по приоритету должно выполнится отрицание, которое приведет к булеву значение, а в свою очередь булево значение будет сравниваться со строкой, что приведет к false

2019-06-05 09:15 UTC, mini4 commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        {
блоки условных операторов и циклов должны начинаться на тех же строках, где и условие или цикл описаны

2019-06-05 09:15 UTC, mini4 commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        {
проверь везде, часто встречаются в этом МР

2019-06-05 09:15 UTC, mini4 commented on komtet.delivery/options.php
> +          if ($value === false)
не надо в php оставлять блоки без скобок, даже если выражение в нем одно

2019-06-05 09:15 UTC, mini4 commented on komtet.delivery/options.php
> +          foreach($arParams as $param)
`foreach ($arParams as $param) {`

2019-06-05 09:15 UTC, mini4 commented on komtet.delivery/options.php
> +          foreach($arSelect as $key => $val)
`foreach ($arSelect as $key => $val) {`

2019-06-06 06:05 UTC, mini4 commented on komtet.delivery/options.php
> +          foreach($arParams as $param) {
пробел после foreach

2019-06-06 15:59 UTC, mini4 commented on komtet.delivery/classes/general/KomtetDelivery.php
> +        if (!$this->shouldForm ) {
лишний пробел

2019-06-10 09:39 UTC, elatonsev approved these changes

2019-06-13 06:06 UTC, mini4 approved these changes

2019-06-13 07:28 UTC, keipaglows approved these changes

2019-06-13 08:07 UTC, closed without merging